#!/bin/bash 

set +e

# Load all the commands 
for cmd in commands/*.sh; do
    echo sourcing $cmd
    . $cmd 
done

usage()
{
cat << EOF
A script for demonstrating the work of camtool utilities 
Usage: $0 -c <cmd> [OPTIONS] 
OPTIONS:
    -c <cmd> command (availble commands are ${CMD_LIST[*]})
    -a <addr> address of the camera 
    -u <username> username for accessing the camera
    -p <password> password for accessing the camera  
    -e <exec> path to executable file for injecting to the camera
    -h display this message
EOF
}

## Varaibles
ADDR=
USERNAME=
PASSWORD=
CMD=
EXEC=
SYS_FW_LIB=
WEBUI_LIB=
SUFFIX=$(mktemp -u .XXXXXXXXXX)
SETTINGS_FILE=/tmp/settings$SUFFIX
EXT_SETTINGS_FILE=/tmp/ext_settings$SUFFIX
NEW_SETTINGS_FILE=/tmp/new_settings$SUFFIX

while getopts “hu:p:a:c:e:s:” OPTION
do
     case $OPTION in
         h)
            usage
            exit 1
            ;;
         a)
            ADDR=$OPTARG
            ;;
         u)
            USERNAME=$OPTARG  
            ;;
         c)
            CMD=$OPTARG
            ;;
         p)
            PASSWORD=$OPTARG
            ;;
         e)
             EXEC=$OPTARG
             ;;
         s)
             SYS_FW_LIB=$OPTARG
             ;;
         ?)
            usage
            exit
            ;;
     esac
done

if [[ -z $CMD ]]; then
  usage
  exit 1
fi


for item in ${CMD_LIST[*]}; do    
    if [[ "$item" == $CMD ]]; then
        run_$CMD
        exit 0
    fi
done
die "Unknown command '$CMD'"

