#ifndef __COMMON_H
#define __COMMON_H

// Web UI related constants 
#define WEBUI_ENTRY_TYPE_FIELD_LEN 1 
#define WEBUI_ENTRY_NAME_SIZE_FIELD_LEN 4

#define WEBUI_FENTRY_SIZE_FIELD_LEN 4

#define WEBUI_FENTRY_MAX_SIZE (WEBUI_ENTRY_NAME_SIZE_FIELD_LEN + MAX_PATH_LEN + WEBUI_ENTRY_TYPE_FIELD_LEN + WEBUI_FENTRY_SIZE_FIELD_LEN + MAX_FILE_SIZE) 

typedef enum {
  OFFSET_MAGIC       = 0x0,
  OFFSET_CHECKSUM    = 0x4,
  OFFSET_SIZE        = 0x8,
  OFFSET_VERSION     = 0xC,
  OFFSET_FIRST_FILE  = 0x10
} header_offset_t; 
//#define WEBUI_DENTRY_SIZE (WEBUI_ENTRY_NAME_FILED_SIZE + MAX_PATH_LEN + WEBUI_FENTRY_TYPE_FIELD_SIZE)

// Function definitions 

#endif  // __COMMON_H
